# controls build options

# enable sensor framework
CONFIG_SENSOR=y
# using Bosch BMP280 (boards/[].overlay specifies BMP over BME)
CONFIG_BME280=y

CONFIG_I2C=y

# logging
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# dbg 
# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y