CREATE TABLE IF NOT EXISTS readings (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          DATETIME DEFAULT CURRENT_TIMESTAMP,
    temperature REAL,
    pressure    REAL
);

CREATE TABLE IF NOT EXISTS commands (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    ts      DATETIME DEFAULT CURRENT_TIMESTAMP,
    command TEXT NOT NULL
);